name: Buildozer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip
        pip3 install cython
        sudo apt-get install -f
        sudo dpkg --configure -a
        sudo apt install -y build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0-0 libgstreamer-plugins-base1.0-dev libunwind-dev
        pip3 install buildozer
        pip3 install git+https://github.com/kivy/python-for-android.git

    - name: Set up Android SDK
      run: |
        mkdir -p $HOME/.buildozer/android/platform/android-sdk
        cd $HOME/.buildozer/android/platform/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O android_cmd_tools.zip
        unzip android_cmd_tools.zip -d cmdline-tools
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/
        yes | cmdline-tools/latest/bin/sdkmanager --licenses
        cmdline-tools/latest/bin/sdkmanager --update
        sudo apt install -y libjaxb-api-java libjaxb-java libjaxp1.3-java
        export JAVA_HOME="/usr/lib/jvm/temurin-8-jdk-amd64"
        export PATH="$JAVA_HOME/bin:$PATH"
        cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;30.0.3"

    - name: Build with Buildozer
      run: |
        buildozer -v android debug
